IF
	OR(6)
		IsOverMe(Player1)
		IsOverMe(Player2)
		IsOverMe(Player3)
		IsOverMe(Player4)
		IsOverMe(Player5)
		IsOverMe(Player6)
	Global("ys_BadPlant","GLOBAL",0)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@408)
		SetGlobal("ys_BadPlant","GLOBAL",1)
END

IF
	!IsOverMe(Player1)
	!IsOverMe(Player2)
	!IsOverMe(Player3)
	!IsOverMe(Player4)
	!IsOverMe(Player5)
	!IsOverMe(Player6)
	Global("ys_BadPlant","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("ys_BadPlant","GLOBAL",0)
END
